const rawData = `SULISMAIK DE SOUZA — R$ 250,00
LUCAS BELATO — R$ 250,00
JOÃO HENRIQUE SOUZA MAGALHÃES — R$ 200,00
ERICA MILENA DA SILVA — R$ 250,00
VITOR OLIVEIRA — R$ 250,00
MARIA CLARA SOUZA COSTA — R$ 220,00
LARA CAVALCANTE SILVA — R$ 220,00
DAVI MIGUEL GOMES DE BRITO — R$ 220,00
KEMILY DE FARIAS OLIVEIRA — R$ 220,00
HEITOR SONAQUE DE SOUZA — R$ 220,00
KAMILA SHAORY RAFAELA CARVALHO — R$ 250,00
ENZO GABRIEL NERY MARQUES — R$ 250,00
RICARDO GABRIEL DE ASSUNCAO — R$ 250,00
LUIS GUSTAVO DA SILVA RIBEIRO — R$ 250,00
GUSTAVO ARRUDA DA SILVA — R$ 250,00
ATAIDE CELESTINO RAMOS DOS SANTOS — R$ 250,00
RODRIGO SOUZA PINTO — R$ 225,00
JADNA DA SILVA LIMA — R$ 250,00
ARTHUR GATZKE KOHLER DE MELO — R$ 125,00
ISAAC GONZAGA MARIO — R$ 250,00
LUANY STEPHANY DE JESUS PORFIRIO GUIMARAES — R$ 250,00
KALEBE LUCAS CARVALHO SILVA — R$ 250,00
RAISSA FERNANDA CASTRO DE LARA — R$ 250,00
ENZO RAFAEL OLVEIRA DA SILVA — R$ 250,00
MATHEUS HENRIQUE DA SILVA PININGA DE SOUZA — R$ 250,00
ACSA LORENA EVANGELISTA SANTIAGO — R$ 320,00
SAMARA CRISTINA DA MOTA SILVA — R$ 250,00
GUILHERME NUNES BARBOSA — R$ 250,00
ANA JULIA MONTEIRO KLEIN — R$ 250,00
EDUARDO ANTONIO — R$ 250,00
RAFAELA MARQUES — R$ 225,00
RAFAELA MARQUES — R$ 225,00
ARTHUR CARVALHO ALVES — R$ 250,00
THEO ANDRADE DE SOUZA — R$ 225,00
SOFYA ANDRADE DE SOUZA — R$ 225,00
PIETRO JORGE DE ALMEIDA — R$ 270,00
CARLOS JUNIOR RONDON LOITERO — R$ 270,00
MAXUEL HENRIQUE DE PAULA CAMPOS — R$ 270,00
WANESSA MIRANDA — R$ 270,00
WILSON FERREIRA DINIZ NETO — R$ 270,00
ARTENISA QUELEM NASCIMENTO — R$ 270,00
ADRIANE MARIA DE OLIVEIRA BRITO — R$ 270,00
DOMILLYCK ALEXANDRE GONCALVES DA SILVA — R$ 270,00
EDVANIA PEREIRA MATOS DA SILVA — R$ 270,00
MATHEUS NASCIMENTO DA CRUZ — R$ 220,00
BRENDA RAILLA GAMA DOS SANTOS — R$ 220,00
BRUNA GAMA DOS SANTOS — R$ 220,00
ELIAS SAMUEL CANDIDO DE SOUZA — R$ 220,00
HELOISA LIMA ESTEVAO — R$ 270,00
DOUGLAS ANTONIO ALMEIDA PEREIRA — R$ 270,00
ELIEZER DAVID — R$ 270,00
ROBSON SOLLES MENDES — R$ 270,00
BENJAMIN KALEB BARBOSA OLIVEIRA — R$ 270,00
REBECA MIKAELI DE CARVALHO BOTONI — R$ 250,00
LUCENE DE JESUS DA SILVA DO NASCIMENTO — R$ 300,00
THAYLA MAYSA SILVA DO NASCIMENTO — R$ 300,00
ANNA SOFIA RAMIRES FERREIRA SAMPAIO — R$ 270,00
ELOIZA MARIA ALVES RAMOS — R$ 270,00`;

const lines = rawData.split('\n').map(l => l.trim()).filter(Boolean);
let sql = '';

for (const line of lines) {
  const [nomeRaw, valorRaw] = line.split(' — R$ ');
  if (!nomeRaw || !valorRaw) continue;
  const nome = nomeRaw.trim().replace(/'/g, "''");
  const valorNum = parseFloat(valorRaw.replace(',', '.'));
  
  let valorCheio = valorNum;
  let valorDesconto = valorNum;
  
  if (valorNum === 250 || valorNum === 270) {
    valorCheio = valorNum + 100;
    valorDesconto = valorNum;
  }
  
  sql += `
UPDATE matriculas m
SET valor_parcela = ${valorCheio}, valor_com_desconto = ${valorDesconto}
FROM alunos a
WHERE m.aluno_id = a.id AND UPPER(a.nome) = '${nome.toUpperCase()}' AND m.status = 'ativa';

UPDATE pagamentos p
SET valor = ${valorCheio}
FROM alunos a
WHERE p.aluno_id = a.id AND UPPER(a.nome) = '${nome.toUpperCase()}' AND p.status = 'pendente' AND p.tipo_receita = 'mensalidade';
`;
}

require('fs').writeFileSync('update_tuitions.sql', sql);
console.log('SQL generated.');
