INSERT INTO gamificacao_conquistas (nome, descricao, pontos, classe, instrumento) VALUES
('Escala Duas Mãos 100bpm+', 'Conseguir executar a escala com as duas mãos a 100bpm', 500, 'Raro', 'Teclado / Piano'),
('Hanon Duas Mãos 100bpm+', 'Conseguir executar o exercício Hanon com as duas mãos a 100bpm', 500, 'Raro', 'Teclado / Piano'),
('Digitação 1358 Mão Esquerda 100bpm+', 'Conseguir executar a digitação 1358 com a mão esquerda a 100bpm', 500, 'Raro', 'Teclado / Piano'),
('Tercina Mão Direita 100bpm+', 'Conseguir executar tercinas com a mão direita a 100bpm', 500, 'Raro', 'Teclado / Piano'),

('Escala Duas Mãos 200bpm+', 'Conseguir executar a escala com as duas mãos a 200bpm', 750, 'Epico', 'Teclado / Piano'),
('Hanon Duas Mãos 200bpm+', 'Conseguir executar o exercício Hanon com as duas mãos a 200bpm', 750, 'Epico', 'Teclado / Piano'),
('Digitação 1358 Mão Esquerda 200bpm+', 'Conseguir executar a digitação 1358 com a mão esquerda a 200bpm', 750, 'Epico', 'Teclado / Piano'),
('Tercina Mão Direita 200bpm+', 'Conseguir executar tercinas com a mão direita a 200bpm', 750, 'Epico', 'Teclado / Piano'),
('Música Completa Teclado', 'Tocar uma música completa no teclado', 750, 'Epico', 'Teclado / Piano'),

('Escala Duas Mãos 300bpm+', 'Conseguir executar a escala com as duas mãos a 300bpm', 1200, 'Lendario', 'Teclado / Piano'),
('Hanon Duas Mãos 300bpm+', 'Conseguir executar o exercício Hanon com as duas mãos a 300bpm', 1200, 'Lendario', 'Teclado / Piano'),
('Digitação 1358 Mão Esquerda 300bpm+', 'Conseguir executar a digitação 1358 com a mão esquerda a 300bpm', 1200, 'Lendario', 'Teclado / Piano'),
('Tercina Mão Direita 300bpm+', 'Conseguir executar tercinas com a mão direita a 300bpm', 1200, 'Lendario', 'Teclado / Piano'),
('Música Difícil Teclado', 'Tocar uma música desafiadora no teclado', 1200, 'Lendario', 'Teclado / Piano'),

('Padrão Escala Quinta Corda 100bpm+', 'Conseguir executar o padrão da escala na quinta corda a 100bpm', 500, 'Raro', 'Cordas (Violão/Guitarra/Baixo)'),
('Padrão Escala Quarta Corda 100bpm+', 'Conseguir executar o padrão da escala na quarta corda a 100bpm', 500, 'Raro', 'Cordas (Violão/Guitarra/Baixo)'),
('Padrão Escala Terceira Corda 100bpm+', 'Conseguir executar o padrão da escala na terceira corda a 100bpm', 500, 'Raro', 'Cordas (Violão/Guitarra/Baixo)'),
('Technique 2x2 Execução Limpa 100bpm+', 'Execução limpa do exercício Technique 2x2 a 100bpm', 500, 'Raro', 'Cordas (Violão/Guitarra/Baixo)'),
('Tercina Quinta Corda 100bpm+', 'Conseguir executar tercina na quinta corda a 100bpm', 500, 'Raro', 'Cordas (Violão/Guitarra/Baixo)'),
('Tercina Quarta Corda 100bpm+', 'Conseguir executar tercina na quarta corda a 100bpm', 500, 'Raro', 'Cordas (Violão/Guitarra/Baixo)'),
('Tercina Terceira Corda 100bpm+', 'Conseguir executar tercina na terceira corda a 100bpm', 500, 'Raro', 'Cordas (Violão/Guitarra/Baixo)'),

('Padrão Escala Quinta Corda 200bpm+', 'Conseguir executar o padrão da escala na quinta corda a 200bpm', 750, 'Epico', 'Cordas (Violão/Guitarra/Baixo)'),
('Padrão Escala Quarta Corda 200bpm+', 'Conseguir executar o padrão da escala na quarta corda a 200bpm', 750, 'Epico', 'Cordas (Violão/Guitarra/Baixo)'),
('Padrão Escala Terceira Corda 200bpm+', 'Conseguir executar o padrão da escala na terceira corda a 200bpm', 750, 'Epico', 'Cordas (Violão/Guitarra/Baixo)'),
('Technique 2x2 Execução Limpa 200bpm+', 'Execução limpa do exercício Technique 2x2 a 200bpm', 750, 'Epico', 'Cordas (Violão/Guitarra/Baixo)'),
('Tercina Quinta Corda 200bpm+', 'Conseguir executar tercina na quinta corda a 200bpm', 750, 'Epico', 'Cordas (Violão/Guitarra/Baixo)'),
('Tercina Quarta Corda 200bpm+', 'Conseguir executar tercina na quarta corda a 200bpm', 750, 'Epico', 'Cordas (Violão/Guitarra/Baixo)'),
('Tercina Terceira Corda 200bpm+', 'Conseguir executar tercina na terceira corda a 200bpm', 750, 'Epico', 'Cordas (Violão/Guitarra/Baixo)'),
('Música Completa Violão/Guitarra', 'Tocar uma música completa de violão/guitarra', 750, 'Epico', 'Cordas (Violão/Guitarra/Baixo)'),

('Padrão Escala Quinta Corda 300bpm+', 'Conseguir executar o padrão da escala na quinta corda a 300bpm', 1200, 'Lendario', 'Cordas (Violão/Guitarra/Baixo)'),
('Padrão Escala Quarta Corda 300bpm+', 'Conseguir executar o padrão da escala na quarta corda a 300bpm', 1200, 'Lendario', 'Cordas (Violão/Guitarra/Baixo)'),
('Padrão Escala Terceira Corda 300bpm+', 'Conseguir executar o padrão da escala na terceira corda a 300bpm', 1200, 'Lendario', 'Cordas (Violão/Guitarra/Baixo)'),
('Technique 2x2 Execução Limpa 300bpm+', 'Execução limpa do exercício Technique 2x2 a 300bpm', 1200, 'Lendario', 'Cordas (Violão/Guitarra/Baixo)'),
('Tercina Quinta Corda 300bpm+', 'Conseguir executar tercina na quinta corda a 300bpm', 1200, 'Lendario', 'Cordas (Violão/Guitarra/Baixo)'),
('Tercina Quarta Corda 300bpm+', 'Conseguir executar tercina na quarta corda a 300bpm', 1200, 'Lendario', 'Cordas (Violão/Guitarra/Baixo)'),
('Tercina Terceira Corda 300bpm+', 'Conseguir executar tercina na terceira corda a 300bpm', 1200, 'Lendario', 'Cordas (Violão/Guitarra/Baixo)'),
('Música Difícil Violão/Guitarra', 'Tocar uma música desafiadora de violão/guitarra', 1200, 'Lendario', 'Cordas (Violão/Guitarra/Baixo)'),

('Rudimento 1234 100bpm+', 'Conseguir executar o rudimento 1234 a 100bpm', 500, 'Raro', 'Bateria'),
('Rudimento 1234 com Bumbo 100bpm+', 'Conseguir executar o rudimento 1234 com bumbo a 100bpm', 500, 'Raro', 'Bateria'),
('Contratempo Chimbal 100bpm+', 'Contratempo no chimbal a 100bpm', 500, 'Raro', 'Bateria'),
('Bumbo no Contratempo 100bpm+', 'Bumbo no contratempo a 100bpm', 500, 'Raro', 'Bateria'),
('Toque Simples 100bpm+', 'Toque simples na bateria a 100bpm', 500, 'Raro', 'Bateria'),
('Toque Duplo 100bpm+', 'Toque duplo na bateria a 100bpm', 500, 'Raro', 'Bateria'),

('Rudimento 1234 200bpm+', 'Conseguir executar o rudimento 1234 a 200bpm', 750, 'Epico', 'Bateria'),
('Rudimento 1234 com Bumbo 200bpm+', 'Conseguir executar o rudimento 1234 com bumbo a 200bpm', 750, 'Epico', 'Bateria'),
('Contratempo Chimbal 200bpm+', 'Contratempo no chimbal a 200bpm', 750, 'Epico', 'Bateria'),
('Bumbo no Contratempo 200bpm+', 'Bumbo no contratempo a 200bpm', 750, 'Epico', 'Bateria'),
('Toque Simples 200bpm+', 'Toque simples na bateria a 200bpm', 750, 'Epico', 'Bateria'),
('Toque Duplo 200bpm+', 'Toque duplo na bateria a 200bpm', 750, 'Epico', 'Bateria'),

('Rudimento 1234 300bpm+', 'Conseguir executar o rudimento 1234 a 300bpm', 1200, 'Lendario', 'Bateria'),
('Rudimento 1234 com Bumbo 300bpm+', 'Conseguir executar o rudimento 1234 com bumbo a 300bpm', 1200, 'Lendario', 'Bateria'),
('Contratempo Chimbal 300bpm+', 'Contratempo no chimbal a 300bpm', 1200, 'Lendario', 'Bateria'),
('Bumbo no Contratempo 300bpm+', 'Bumbo no contratempo a 300bpm', 1200, 'Lendario', 'Bateria'),
('Toque Simples 300bpm+', 'Toque simples na bateria a 300bpm', 1200, 'Lendario', 'Bateria'),
('Toque Duplo 300bpm+', 'Toque duplo na bateria a 300bpm', 1200, 'Lendario', 'Bateria'),

('Lip Trill 20s+', 'Manter Lip Trill por mais de 20s', 500, 'Raro', 'Técnica Vocal'),
('ZZZ 20s+', 'Manter ZZZ por mais de 20s', 500, 'Raro', 'Técnica Vocal'),
('SSS 20s+', 'Manter SSS por mais de 20s', 500, 'Raro', 'Técnica Vocal'),

('MA ME MI MO MU Contínuo', 'Executar padrão MA ME MI MO MU de forma contínua', 750, 'Epico', 'Técnica Vocal'),
('Afinação Vocal', 'Manter a afinação precisa nos exercícios vocais', 750, 'Epico', 'Técnica Vocal'),
('Modulação Vocal', 'Realizar a modulação vocal com suavidade', 750, 'Epico', 'Técnica Vocal'),

('Leitura de Cifras Avançada', 'Leitura dinâmica e rápida de cifras', 500, 'Raro', 'Teoria Musical'),
('Prática com Metrônomo', 'Dominar a prática constante utilizando metrônomo', 500, 'Raro', 'Teoria Musical'),
('Tocar com VS', 'Conseguir tocar uma música com VS (Virtual Studio)', 500, 'Raro', 'Teoria Musical'),
('Tirar de Ouvido', 'Tirar uma música simples de ouvido', 500, 'Raro', 'Teoria Musical'),
('Inversão de Acordes', 'Montar inversões de acordes maiores e menores', 500, 'Raro', 'Teoria Musical'),
('Localização no Teclado', 'Localizar rapidamente as notas no teclado', 500, 'Raro', 'Teoria Musical'),
('Localização no Violão', 'Localizar rapidamente as notas no braço do violão', 500, 'Raro', 'Teoria Musical'),
('Reconhecimento das Notas Musicais', 'Reconhecimento visual imediato das notas', 500, 'Raro', 'Teoria Musical');
